### PR TITLE
WIP : compatibility with tmux 2.9

### PR DESCRIPTION
**Pull request by koalp**
This is a work in progress pull request to update this theme to work with tmux 2.9

- [x] update bg and fg attributes
- [ ] update `attr "none"`

### CODE REVIEW

**Comment by polyzen** [comment]
https://github.com/tmux/tmux/wiki/FAQ#how-do-i-translate--fg--bg-and--attr-options-into--style-options

**Comment by koalp** [comment]
Thank you, but when I change to (like in my commit), i do not obtain the same result than in 1.8 .
I still need to investigate to see how to obtain the wanted result.

# In 1.8
tmux with tmux-gruvbox  in 1.8
# In 1.9 without setting the `none` attributes
tmux with tmux-gruvbox patched on fg and bg only in 1.9
# In 1.9 with the none attributes
tmux with tmux-gruvbox, trying to patch none in 1.9, but it doesn't work

**Comment by koalp** [comment]
I pushed a hacky workaround. 
It works but I don't really know why.

**Comment by egel** [comment]
I think I've managed to update the dark theme according to breaking changes in tmux v2.9. See this PR in #8.

**Pull request closed without merging**
